buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://files.minecraftforge.net/maven' }
        maven { url 'https://cdn.fox2code.com/maven' }
    }
    dependencies {
        classpath('com.fox2code.FoxLoader:dev:2.0-alpha34')
    }
}

apply plugin: 'foxloader.dev'

group = 'com.kingcolton1'
version = '1.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation('com.github.Vatuu:discord-rpc:1.6.2') {
        exclude group: 'org.lwjgl.lwjgl'
        exclude group: 'org.lwjgl'
    }
}

test {
    useJUnitPlatform()
}

jar {
    from "LICENSE"
    
    // Include dependencies in the JAR
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    
    exclude 'org/lwjgl/**'
    exclude 'org/lwjgl/*'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

foxloader {
    modId = "reindevdiscordrpc"
    modName = "ReIndev Discord RPC"
    modIcon = "assets/reindevdiscordrpc/icon.png"
    modVersion = project.version
    modAuthors = "KingColton1"
    modWebsite = "https://github.com/KingColton1/ReIndev-Discord-RPC/"
    modMain = "com.kingcolton1.reindevdiscordrpc.ReindevDiscordRPC"
    modDesc = "Discord RPC for ReIndev"
}
